url: https://www.muchen.ca

markdown: kramdown

kramdown:
  auto_ids: true
  enable_coderay: false
  hard_wrap: false
  input: GFM

sass:
  style: compressed

# Plugins
plugins:
  - jemoji
  - jekyll-sitemap

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: <!-- excerpt -->
      nav_active: /blog
      permalink: /:categories/:year/:title/
  - scope:
      path: "documents"
    values:
      layout: doc
      nav_active: /documents
  - scope:
      path: ""
    values:
      author: Muchen He

collections:
  photos:
    output: true

use_image_as_brand: false