# Build config
incremental: false

# Site config
title: "Muchen He"
description: "Website showcasing Muchen's projects and school notes."
url: https://www.muchen.ca
author: Muchen He
logo: "/assets/img/light-512.jpeg"

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids: true
  enable_coderay: false
  hard_wrap: false
  input: GFM

# Styling
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  - scope: # default for everything across the site
      path: ""
    values:
      show_navigation: true
      show_footer: true
  - scope: # stuff under _posts folder
      path: ""
      type: "posts"
    values:
      layout: post
      excerpt_separator: <!-- excerpt -->
      nav_active: /blog
      permalink: /blog/:year/:title/
  - scope:
      path: "documents"
    values:
      layout: doc
      nav_active: /documents
      use_category_instead_of_name: true
      show_footer: false
  - scope:
      path: ""
      type: "photos"
    values:
      nav_active: /photos
      permalink: /photos/:year/:title
      use_lightbox: true
      excerpt_separator: <!-- excerpt -->

# Collections config
collections:
  photos:
    output: true

use_image_as_brand: false