#TODO: Responsive navbar

application: moochhe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static
- url: /fonts
  static_dir: static/fonts

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /(.*\.(gif|png|jpg|ico|bmp|html|css|js))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|bmp|html|css|js))

- url: /static/(.*\.(gif|png|jpg|ico|bmp|html|css|js))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|bmp|html|css|js))

# Landing page
- url: /
  static_files: static/landing.html
  upload: static/landing.html

# machine learning notes
- url: /ml
  static_files: static/machine-learning-notes.html
  upload: static/machine-learning-notes.html

# portfolio
- url: /portfolio
  static_files: static/portfolio.html
  upload: static/portfolio.html

# processing
- url: /p5
  static_files: static/p5/index.html
  upload: static/p5/index.html

# Dynamic
- url: /home
  script: main.app

- url: /login
  script: login.app

- url: /test
  script: test.app

# 404
- url: /.*
  static_files: static/not_found.html
  upload: static/not_found.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
