#TODO: Responsive navbar

application: moochhe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|bmp|html|css|js))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|bmp|html|css|js))

# home
- url: /
  static_files: index.html
  upload: index.html

# 404
- url: /.*
  static_files: static/not_found.html
  upload: static/not_found.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
